version: '3.8'

services:
  db:
    image: postgres:15
    container_name: saferxai_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: saferxai_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  api:
    build: .
    container_name: saferxai_backend
    restart: always
    depends_on: 
      - db
    env_file:
      - .env
    environment:
      - GIT_PYTHON_REFRESH=quiet
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
  
  frontend:
    build:
      context: ./frontend
    container_name: saferxai_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: